module.exports = {
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  GOOGLE_PHOTOS_REFRESH_TOKEN: process.env.GOOGLE_PHOTOS_REFRESH_TOKEN,
};