media_folder: "src/assets/imgs/uploads"
public_folder: "/assets/imgs/uploads"
display_url: /
site_url: https://fotos.hoeser.dev
collections:
  - name: events
    label: Events
    label_singular: Event
    folder: src/events
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["date", "title"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Verstecken",
          name: "eleventyExcludeFromCollections",
          widget: "boolean",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          required: false,
          options: ["Einrad", "Handball"],
        }
      - {
          label: "Fotografen",
          name: "photographers",
          widget: "select",
          multiple: true,
          required: false,
          options: ["Kim", "Liz", "Thomas"],
        }
      
      - name: cover
        label: Cover
        widget: image
        required: false
      - name: google_photos
        label: Google Photos
        widget: list
        collapsed: false
        required: false
        fields:
          - name: name
            label: Titel
            widget: string
          - name: url
            label: URL
            widget: string
          - name: cover
            label: Cover
            widget: image
            required: false
      - { label: "Body", name: "body", widget: "markdown", required: false }

backend:
  name: git-gateway
  branch: main
local_backend: true
